spring:
  application:
    name: user-service
  config:
    import: 
      - optional:configserver:http://localhost:8888
  #     - vault://
  # cloud:
  #   vault:
  #     uri: http://localhost:8200
  #     token: ${VAULT_TOKEN}
  #     kv:
  #       enabled: true
  #       backend: secret
  #       default-context: user-service
  #       application-name: user-service
  #     fail-fast: false